### ISSUE TITLE
Slow Commits When Using Batches of Messages

### ISSUE THREAD

**Issue by dbcfd** [akka/alpakka-kafka#272]
See comment below. Code was just sending 1 offset, but either offset rollup in commitable batch of conversion of offset result is causing slow consumption.

**Comment by dbcfd** [comment]
This may be from updating CommittableOffsetBatchImpl: https://github.com/akka/reactive-kafka/blob/master/core/src/main/scala/akka/kafka/internal/ConsumerStage.scala#L156

**Comment by ennru** [comment]
I looked into your PR #273 now and can see a slight chance that the current code in certain situations could overwrite a higher commit offset with a lower one. So the logic to take the max of the current value in the offsets map and the incoming one could make sense.
For the rest of the PR I don't get enough motivation in this issue description and the code has moved forward a lot since you opened it.
I'll close both the PR and this issue, please reopen if you can provide more background.
