### ISSUE TITLE
Timer of GroupedWithin does not seem to be working

### ISSUE THREAD

**Issue by gantamk** [akka/alpakka-kafka#364]
Hello All,

Timer of GroupedWithin does not seem to be working. In this example, I am not getting any messages even after expiry of duration (10 seconds) even though 7 items are available in Kafka. If I produce 3 more items, then I am getting the entire desired batch (10 items). Please see the snippet below. 
  
akka & akka streams Version = "2.4.19"
akka-stream-kafka Version = "0.17"

Thank you.

```
Consumer.committableSource(consumerSettings, Subscriptions.topics("topic-1"))
      .groupedWithin(10, 10.seconds)
      .mapAsync(1) { group =>
        val msgs =  group.toList.map(_.record.value())
        saveToDB(msgs )
      }
      .map(group => group.foldLeft(CommittableOffsetBatch.empty) { (batch, elem) => 
      batch.updated(elem.committableOffset) 
      })
      .mapAsync(3)(_.commitScaladsl()) 
      .runWith(Sink.ignore)
```

**Comment by gantamk** [comment]
And below normal akka-streams snippet gives desired result without any issues

```
object SourceTest extends App {

  import scala.concurrent.ExecutionContext.Implicits.global

  implicit val system = ActorSystem("system1")
  implicit val materializer: ActorMaterializer = ActorMaterializer()

  val counter = new AtomicInteger(0)
  Source
    .tick(initialDelay = 0.nanos, interval = 1.seconds, tick = ())
    .map { _ =>
      counter.incrementAndGet()
    }
    .groupedWithin(10, 5.seconds)
      .mapAsync(1) { result =>
        println("results :" +result.toList)
        Future.successful(result)
      }
    .runWith(Sink.ignore)
    .onComplete { _ =>
   // system.shutdown()
  }
}
```

**Comment by gantamk** [comment]
Hello Everyone,
Any response to above will be greatly appreciated. 
Thank you.

**Comment by patriknw** [comment]
strange, it would be interesting to see a failing test in https://github.com/akka/reactive-kafka/blob/master/core/src/test/scala/akka/kafka/scaladsl/IntegrationSpec.scala

**Comment by gantamk** [comment]
I have a test in my code, I can share that. Or I can clone and setup in above suggested spec. Please let me know.

**Comment by patriknw** [comment]
it would be great if you can create a PR with such test added to IntegrationSpec, if it's a bug such test must be written anyway

**Comment by ennru** [comment]
Did you manage to isolate this problem into test cases?
Please re-open, if you still experience this.

**Comment by graphex** [comment]
I seem to be encountering this with 0.22 in cases where there are no new messages coming in to the kafka topic, the final groupedWithin never seems to finish.

**Comment by ennru** [comment]
Thank you for reporting your issue with this. I'll re-open.

**Comment by nayakravi** [comment]
We are seeing this behavior in akka v2.6.5 with akka kafka v2.0.2 with the CommitterSink, which internally uses groupedWeightedWithin. But the symptoms are the same. Our workload is such that we get a burst of messages at the top of the hour, which get processed in about 20-25 minutes. Then the application idles until the next hour and so on. However, we always see a lag even when it has finished processing all the records - we verified by checking the database (I even logged every offset in a low volume setting and ensured that all the records were processed) and passed the offsets downstream to this sink. This happens when there aren't enough messages to complete the last batch. Our expectation was that when maxInterval elapses, it should commit the last batch.

**Comment by ennru** [comment]
As Alpakka Kafka now for has the `groupedWithin` built-in in the `Committer.flow`. I'll close this again.
If you see problems with `groupedWithin`, report it with a reproducer in https://github.com/akka/akka/issues, please.
