### ISSUE TITLE
API naming improvements

### ISSUE THREAD

**Issue by patriknw** [akka/alpakka-kafka#424]
Some naming in the API is not nice, such as `commitJavadsl` and `commitScaladsl` and now I noticed new things added with similar naming convention.

**Comment by ktoso** [comment]
Yeah; I followed existing style in the new https://github.com/akka/reactive-kafka/pull/423
Not quite sure what we should do about it.

On one hand, it would be best to have complete javadsl/scaladsl split as we have in most Akka APIs, but that would be breaking APIs.

If naming change, then the same should be applied to commitJavadsl I etc perhaps?
Open for ideas, was pondering it a bit and did not figure out a nice solution without breaking people's code so far

**Comment by ktoso** [comment]
Thankfully we were able to avoid adding another method with "javadsl" in the name.
Ticket remains valid

**Comment by ennru** [comment]
A non-API-breaking way to hide the `commitScaladsl`/`commitJavadsl` methods is to introduce a flow eg. `Committer` that does it behind the scenes.
It could offer pre-packaged `groupedWithin` and other useful patterns.

**Comment by patriknw** [comment]
I like that idea, including the added convenience.

**Comment by ennru** [comment]
With where we are today, users should not interact with the `commitJavadsl` and `commitScaladsl` methods. We could even deprecate them, I believe.

**Comment by seglo** [comment]
> We could even deprecate them, I believe.

Yes, they only ever offered the illusion of control anyway.  Let's deprecate them. :+1:

**Comment by ennru** [comment]
With the deprecation of the old methods in #959 we can close this.

**Comment by chetankm-cs** [comment]
@seglo 

> Yes, they only ever offered the illusion of control anyway. Let's deprecate them. 👍

Can you explain this a little bit, at my work we were relying on these apis to handle commit failures as restarting the committer flow can cause commits to be missed.

**Comment by seglo** [comment]
Hi @chetankm-cs 

> Can you explain this a little bit, at my work we were relying on these apis to handle commit failures 

That's interesting. How do you handle commit failures when they're observed?

> as restarting the committer flow can cause commits to be missed.

Were you using [`RestartFlow.onFailuresWithBackoff`](https://doc.akka.io/docs/akka/current/stream/operators/RestartFlow/onFailuresWithBackoff.html)? I don't think I've seen this use before with the committer flow, but it makes sense that it could cause commits, from the docs:

> The restart process is inherently lossy

Alpakka Kafka committing is fairly robust.  It will retry commits if they happen to fail (added recently in #1111).  If you receive any non-retriable exception during the commit process it's probably due to network partitions, in which case restarting the whole stream might be the best approach.

The reason we want to deprecate the methods is because they give the user a false sense that offsets will be committed as soon as they call the `commit{Java|Scala}dsl` method, when what actually happens is commits are batched in the `KafkaConsumerActor` and committed on the next poll interval.  This change was made so we don't overwhelm the broker with too many offset commit requests.

**Comment by chetankm-cs** [comment]
@seglo  Thanks for the quick reply.

I was under the assumption that `commitScaladsl ` commits to kafka, so I added logic to retry `commitScaladsl` future on failure. 
Also in case of any unexpected failures I was using `RestartFlow.onFailuresWithBackoff` to restart the stream. 

Is there a way to manually commit the offset, given we are okay with low throughput.
