### ISSUE TITLE
Adapt poll interval to demand

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#559]
Out of the analysis for #549, I think it would be interesting to explore if the `KafkaConsumerActor` could adapt the poll interval to the downstream demand.
Calling `poll()` regularly is required to let the Kafka cluster know the consumer is still alive (heartbeat), even if no other communication is pending.
But there is no reason to keep polling every 50 milliseconds (the default) when there is nothing to say and no demand.

**Comment by zaharidichev** [comment]
@ennru 
I would like to help with this. Correct me if my understanding is wrong but after reading the analysis provided by you and @adkafka, I came to the conclusion that the main problem comes from the pipelining effect that the Kafka Fetcher tries to achieve. In a sense when we poll and we grab some fetched data from the consumer, the Fetcher issues another fetch request right away. Due to the fact that our polling interval is quite tight, we end up in a situation where we pause the partition for which this fetch request has been issues before it has been completed. So once the records come back they are "no longer fetchable"... So really this likelihood of this wasteful data transfer not happening is a function of how much a fetch request takes to complete and out own poll interval (which happens to pause the partition as well...).  Again.. correct me if I am not understanding this..

In my mind adapting the poll interval to the demand can have a positive effect, but then again that needs to be done while taking consideration of the maximum a `max.poll.interval.ms`. Additionally draining fetched records into a buffer does not seem possible with the current version of the driver. So I am not sure what kind of caching we can implement in the `KafkaConsumerActor ` that can help us...  

Ofcourse, the ideal scenario would be if we had a mechanism for firing heartbeats that is not so tightly coupled with consumption. There have been however several proposals for introducing such functionality in the consumer but they all have been rejected for a reason.  

That being said, I am a bit lost while trying to think of a "silver bullet" solution which is not relying on manipulating settings and hoping that stars align. You however have looks a bit more into this so if you have any other ideas you want to share, I would be more than happy to experiment with them.

**Comment by ennru** [comment]
Yes, your description of what I understood from looking into it is perfectly right. 

I haven't followed up anything more on the idea of a more dynamic poll interval. We want the tight polling when there is a lot of data coming by, but can get slower when demand drops. There are many constraints to it and we need to be very careful here.

Following Lightbend's [current plan](https://github.com/akka/akka-meta/issues/83) for Alpakka we're working hard on the Kafka connector to improve test scenarios and improve the code for easier understanding. 

I'd love to get help from you and others out there to try different ideas to improve this misbehaviour. You seem to have some insight into inner workings of the Kafka consumer, but I guess relying on internals there is dangerous business when it comes to upgrading. (We just merged the Kafka 2.0.0 upgrade.)

**Comment by zaharidichev** [comment]
@ennru @adkafka
After a bit of thinking and some experimentation, I think I understand the problem a bit better. Took a better look at your test case that you have referenced to and that was quite helpful. The thing is that even if we adapt the poll interval to be dependant on demand, there is little we can do to solve the problem. 

In the test case that you have created we have a single consumer actor and the discarded fetches are solely caused by the fact that we have the scheduled poll. Of course that could be solved by adjusting the polling interval and taking into consideration the max poll interval that kafka has been configured with. 

Things stand differently however if this actor is shared by multiple streams. In that case if one of the stream consumers is much slower than the other one, the fast consumer will pretty much behave similarly to the scheduled poll in your example. As you probably imagine this is not subject to adjustment. Things become even worse if we have many streams sharing the actor. This can probably cause quite a lot of data to be discarded (in case we have high variance of demand request frequency among different consuming streams).

The former is clearly illustrated with the example that I have put together (based on your original work): https://github.com/ennru/alpakka-kafka/pull/1/files Note that I have manually set the poll interval to 10 minutes here, so we effectively do not have poll interval. However if you run the test, you will see that fetched data is still discarded because the poll of the faster consumer makes the fetcher drain its buffer of prefetched records (as pointed out by @patriknw ). 

I think this is a rather undesirable scenario that can however occur oftenly. The only definite solution I see is to issue a KIP to the Kafka Java driver with a proposal to introduce a setting of type `discard-prefetched-data-for-paused-topic-partitions = true`. Defaulting this to true will keep the exact sae behaviour as now. If it is false, the prefetched data of paused partitions shall be returned as if its a normal poll on an unpaused partition. As this will happen only once per resume-pause-resume cycle and as we are guaranteed to aways have a configurable, bounded number of prefetched elements, it is safe to cache that in the consumer actor and use it instead of throwing it away. I think this is a change that makes sense and that would allow us to solve this problem. Let me know what you guys think and whether its worth putting in the KIP. If this is an effort worth going through, I can take it on and follow up on the kafka driver as well as the alpakka change. Cheers :)

**Comment by ennru** [comment]
Great analysis! 
Now that you say it, it is obvious that a shared actor can't adapt the poll interval to low demand in a good way.

I've started to look into the changes introduced by the [Kafka client 2.0](https://cwiki.apache.org/confluence/display/KAFKA/KIP-266%3A+Fix+consumer+indefinite+blocking+behavior), especially the new behaviour for `poll(Duration)`. We'll need to re-think the polling without demand here:

> One notable usage is prohibited by the new poll: previously, you could call poll(0) to block for metadata updates, for example to initialize the client, supposedly without fetching records. Note, though, that this behavior is not according to any contract, and there is no guarantee that poll(0) won't return records the first time it's called. Therefore, it has always been unsafe to ignore the response.

I've created #608 to track that work.

> What particular constraints are you talking about (apart from the heartbeat constraint?)

We want to get notified on partition re-balancing (especially important for partitioned sources). The `max.poll.interval` is the upper limit of course. I'm not sure what else we need to keep in mind.

**Comment by zaharidichev** [comment]
Yes, I have read about the new version, lets discuss in #608. However this mainly concerns the poll(0) calls as well as the wake up behaviour. Still does not solve the [problem of throwing fetched data. If there are any other ideas for solving that apart from the one proposed, feel free to share :)

**Comment by ennru** [comment]
The best solution would definitely be to improve the Kafka client and get some control over the prefetched data.
What I find relevant to explore is the new `poll(Duration.ZERO)` behaviour as it now may return data that is in the pipe already. How does it relate to prefetching and pausing?

**Comment by zaharidichev** [comment]
@ennru 
I agree its quite important to consider. Looking at the code more closely, we are pretty much guaranteed that `poll(Duration.ZERO)` will not return data for partitions that are paused. So if there is a partition that holds some prefetched records, calling `poll(Duration.ZERO)` will return the data only if the partition is not paused. If its is paused, it will ignore the prefetched records. Pretty much same as the current behaviour. They are pretty much warning that poll(Duration.Zero) does not guarantee not returning data.

**Comment by zaharidichev** [comment]
@ennru 

I did reach out on the mail list describing the problem in detail and the response that I got was not really what I hoped for: 

> Zahari,
> 
> It sounds to me like this problem is due to Akka attempting to implement
> additional backpressure on top of the Consumer API. I'd suggest they not do
> that, and then this problem goes away.
>  

Seems to me they are referring to the quotas functionality but I do not think that this can help us a lot.

**Comment by ennru** [comment]
I'm not sure I understand what this answer says. Do you have a link to the discussion on that list?
It might be that we are too concerned about how easily the Kafka client code may block, as it had this indefinite blocking behaviour in the past. But we need to understand what to expect from the changes.

**Comment by zaharidichev** [comment]
I don't think the answer says much overall... Here is the link: https://lists.apache.org/thread.html/fbb7e9ccc41084fc2ff8612e6edf307fb400f806126b644d383b4a64@%3Cdev.kafka.apache.org%3E

Simply skipping to call the poll  (as suggested )when we are not ready for records is a brutal oversimplification of what needs to happen and not an option at all because: 

- You need to call it at certain point in order to indicate liveliness
- You might want to call it and get records for one topic partition but skip all others that are paused (without throwing away all the data that has been previously transmitted over the wire). 

In any case,  I will follow up on this discussion if you don't mind and see where it gets us.

**Comment by ennru** [comment]
Thank you for the link. I get the impression that the person did not really try to understand the question you had.
As you say, even if a client has no demand for data at all, it needs to keep calling `poll`. I guess the non-standard use case our Kafka connector has, is to apply different flow control to different topics within one client instance.

**Comment by zaharidichev** [comment]
Yes, I think my question was not really taken very seriously. Never mind I will push until I get a proper answer. But yes, we need to keep calling poll. On top of  that the use case of the akka connector applying different priorities to topic within the same client instance does not strike me as so non trivial. After all the documentation states very clearly that this is the precise use case for the pause/resume API. Will me monitoring the thread

**Comment by zaharidichev** [comment]
I submitted a KIP for that [here](https://cwiki.apache.org/confluence/display/KAFKA/KIP-385%3A+Provide+configuration+allowing+consumer+to+no+throw+away+prefetched+data). There is a link to the [maillist discussion](https://lists.apache.org/thread.html/e463cc04fb7e4d86e4e0d577ccaa0fe06b334c3233b281582e730c22@%3Cdev.kafka.apache.org%3E) associated with the KIP as well

**Comment by 2m** [comment]
@zaharidichev thank you very much for handling this in the mailing list and eventually KIP, which pinged linkedin to push the fix upstream here: https://github.com/apache/kafka/pull/5844/files

**Comment by zaharidichev** [comment]
Yes it turned out quite nice, albeit I was hoping to push a fix myself, but they raced me to it. Nevermind, will focus on #614 now. All is well when it ends well :)

**Comment by ennru** [comment]
This conclusion is that there is no good way to adapt the poll interval dynamically when we share the `KafkaConsumerActor` across multiple streams as demand may vary.
The issue which I thought we could improve upon will hopefully be fixed in Kafka with https://github.com/apache/kafka/pull/5844

I'll close this.
