### ISSUE TITLE
Create example showing Akka Cluster and Kafka topic partitions

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#566]
The docs should show an example exercising Akka Cluster together with the Kafka connector listening to all partitions of a topic on different nodes. Possibly using Akka Cluster Sharding, as well.

**Comment by patriknw** [comment]
I agree that it should be documented, but isn't ordinary consumer groups enough in most cases. See "Consumer Groups and Topic Subscriptions" in
https://kafka.apache.org/10/javadoc/?org/apache/kafka/clients/consumer/KafkaConsumer.html

It means that you can start a consumer on each node in the cluster, using the same group-id, then Kafka will balance the partitions over the active consumers. Scaling by adding more nodes. This by itself doesn't even require Akka Cluster. Did I misunderstand something?

**Comment by SemanticBeeng** [comment]
> _"doesn't even require Akka Cluster."_
The way I understand the question, it would be useful to create a pair of examples that is functionally equivalent modulo the way remoting is done:.

`Kafka` now has _"exactly once delivery semantics"_ which makes it superior to remote actor calls.
https://www.confluent.io/blog/exactly-once-semantics-are-possible-heres-how-apache-kafka-does-it/ 
_"Exactly once semantics: even if a producer retries sending a message, it leads to the message being delivered exactly once to the end consumer. Exactly-once semantics is the most desirable guarantee, but also a poorly understood one. This is because it requires a cooperation between the messaging system itself and the application producing and consuming the messages"_

And for `Akka`
 * https://manuel.bernhardt.io/2018/01/31/tour-akka-cluster-eventual-consistency-persistent-actors-message-delivery-semantics/
 * https://developer.lightbend.com/blog/2017-08-10-atotm-akka-messaging-part-1/index.html
 * https://developer.lightbend.com/blog/2017-11-01-atotm-akka-messaging-part-2/index.html
> _"For now, consider that implementing an exactly-once messaging solution is on the same level as creating a vehicle that can travel faster than the speed of light. There are ways to get close, that is to deliver messages essentially-once but it is impossible to implement an exactly-once process that works."_ 

Thoughts ?

**Comment by TimMoore** [comment]
@patriknw while using Akka Cluster is not strictly required for distributing topic consumption over several nodes, I think it's common to combine Kafka consumers with sharded actors for processing the messages.

**Comment by ennru** [comment]
@SemanticBeeng I'm not sure I'm following. How does remoting come into the picture and how is it related to Kafka supporting transactions (which we leverage as described in [Transactions](https://doc.akka.io/docs/akka-stream-kafka/current/transactions.html))?
Feel free to have this more general discussion [on the forum](https://discuss.lightbend.com/c/akka/streams-and-alpakka).

**Comment by SemanticBeeng** [comment]
Will review and reconsider my ask @ennru. 
Nothing on this issue suggested a context strictly about "transactions" - what did I miss?

**Comment by SemanticBeeng** [comment]
> common to combine Kafka consumers with sharded actors for processing the messages.
@TimMoore please provide best such examples if any public. I am looking to compare from "message delivery semantics" point of view.

These seems to have different takes on whether "exactly once delivery semantics" is possible.
https://developer.lightbend.com/blog/2018-02-01-atotm-akka-messaging-part-3/index.html
https://www.confluent.io/blog/exactly-once-semantics-are-possible-heres-how-apache-kafka-does-it/

**Comment by ennru** [comment]
[Aligning Kafka Partitions with Akka Cluster Sharding](https://github.com/akka/akka-samples/tree/2.6/akka-sample-kafka-to-sharding-scala) shows how to bring Akka Cluster Sharding and Kafka partitions together!
