### ISSUE TITLE
Detect if broker is available (when using Kafka 2.x client)

### ISSUE THREAD

**Issue by ennru** [akka/alpakka-kafka#674]
When using the new Kafka consumer API from Kafka 2.x, we won't use `WakeupException`s anymore to stop the client from blocking the actor thread.
Until now theses exceptions served as an indication that there was now Kafka broker available, or that it disappeared. This won't be detected automatically with the new API use.
For use cases where we actually want to fail the consuming stream when there is no Kafka broker, a regular call to `listTopics(Duration)` would be able to check the connection.
(As suggested on [StackOverflow](https://stackoverflow.com/questions/37920923/how-to-check-whether-kafka-server-is-running))

**Comment by mriehl** [comment]
Hi,

We noticed that when a broker is assigned a new IP (due to machine failure for example), the source never fails anymore. This is an issue because the kafka consumer library will cache the broker `InetSocketAddress`es on startup, and never update them again.
We have a retry backoff supervision around the consumer source that will re-create it if the stream blows up. This used to work because the source would blow up, and then our supervision would recreate it which causes the kafka consumer to resolve the broker IPs anew.

The new API is pretty terrible, because now the source never fails. And since it doesn't fail, we don't recreate it and the kafka consumer keeps its resolved broker `InetSocketAddress` forever.

**Comment by mriehl** [comment]
Damn, I was pretty sure I was using the latest from maven central but apparently still on `1.0`. I'll upgrade and see what happens, but it really looks like they solved it. Thanks!

**Comment by mriehl** [comment]
Can confirm using 1.0.1 solves the issue

**Comment by ennru** [comment]
I'm glad to hear that. Thanks for getting in touch.

**Comment by gabrielgiussi** [comment]
@ennru could I give it a try?

**Comment by ennru** [comment]
Sure, that would be great.

**Comment by tayvs** [comment]
@gabrielgiussi @ennru Is there any updates?

**Comment by ennru** [comment]
This could possibly be implemented together with https://github.com/akka/alpakka-kafka/issues/765

**Comment by tayvs** [comment]
As were mentioned, `listTopics` can be used to check connectivity. 
What if there was a scheduler that periodically checks `listTopics` and in case of failure retries exponentially configurable number of attempts. After attempts exceeded, `KafkaConsumerActor` stops and `processErrors` signals all stages, thus stream fails.

**Comment by ennru** [comment]
Sounds viable. But that should be implemented in another actor so that it can be amended with another dispatcher and easily replaced with other strategies.

How would it work for producers?

**Comment by tayvs** [comment]
@ennru 
Regarding producers. 
Correct me if I'm wrong, producer fails the stream with `TimeoutException` after an attempt of issuing message when there is no alive connection to broker. That is, there is already kind of liveness check in producers, "deferred" though.

**Comment by ennru** [comment]
Ok, that is probably enough.

**Comment by tayvs** [comment]
Thanks, then I'll try to contribute.

**Comment by ennru** [comment]
Implemented with #831
