### ISSUE TITLE
Client Not Following Broker IP Change - Upgrade Kafka Client to 2.1.1

### ISSUE THREAD

**Issue by mehdimas** [akka/alpakka-kafka#734]
### Versions used 
Alpakka Kafka version: 1.0

Akka version: 2.5.21

Kafka version: 2.1.0

### Expected Behavior

If a Kafka broker changes IP after a Kafka client has resolved the broker's IP, the client should re-resolve the broker's new IP address and reconnect.

### Actual Behavior

The Kafka client tries to reconnect to the old broker IP forever. A restart of the client is required to resolve the issue.

### Work Around

Include "org.apache.kafka" % "kafka-clients" % "2.1.1" explicitly to upgrade the Kafka client.

### Relevant Information

Closed bug ticket on Kafka's issue tracker: https://issues.apache.org/jira/browse/KAFKA-7755

This behavior exists in the 2.1.0 Kafka client. There is a release for Kafka 2.1.1 that resolves this issue.

The fix has been validated in our production environment.

**Comment by 2m** [comment]
Thank you for reporting and for listing the workaround.

**Comment by marcoakeller** [comment]
Hi, how this can be handled using Spark since the latest version is still 2.0.0?

**Comment by seglo** [comment]
This particular issue isn't applicable to the Kafka client before Kafka 2.1.0 (according to the [Kafka Jira issue](https://issues.apache.org/jira/browse/KAFKA-7755)), because it was caused by a feature introduced in 2.1.0 and fixed in 2.1.1.

> Since 2.1.0 Kafka clients are supporting multiple DNS resolved IP addresses if the first one fails. This change has been introduced by https://issues.apache.org/jira/browse/KAFKA-6863.

I'm not sure how Spark would handle this situation in practice.  I suspect the particular executor would (with a Kafka consumer) would fail and hopefully resolve the correct IP when it starts back up.
