### ISSUE TITLE
Handle all exceptions from Kafka Consumer

### ISSUE THREAD

**Issue by 2m** [akka/alpakka-kafka#796]
### Description

Currently exceptions from Kafka Consumer in KafkaConsumerActor are handled by ad-hoc basis (exceptions from `poll`, `subscribe` are handled but not others). If such exception is not handled, then it is escalated to the system guardian which restarts the actor. However stream backed up by the actor is never failed and the exception is not propagated.

**Comment by kpmeen** [comment]
I'm encountering this for connecting to a secure Kafka cluster, I think. When the wrong credentials are provided a message is logged from the Kafka `NetworkClient` saying `failed authentication due to: Authentication failed: Invalid username or password`. This continues until the process is stopped or killed.
Is there a way to work around this somehow?

**Comment by tayvs** [comment]
@2m Is it solution if create parent actor for error handling using supervisor strategy and propagate errors to dependent streams or everything more difficult

**Comment by ennru** [comment]
I think wrapping in try-catch whenever the consumer is called is the way to go here.

**Comment by ennru** [comment]
Implemented with #887.
