### ISSUE TITLE
Investigate different consumer group rebalance strategies

### ISSUE THREAD

**Issue by seglo** [akka/alpakka-kafka#943]
### Short description

It's been observed that every time an Alpakka Kafka source app is run that all partitions are first revoked before assignments take place.  We should investigate why this is the case and if this is normal behaviour.

### Details

Explore the default consumer group rebalance strategies.  According to Kafka docs the default strategy is defined by the consumer property `partition.assignment.strategy`, with a default of `class org.apache.kafka.clients.consumer.RangeAssignor` (https://kafka.apache.org/23/javadoc/org/apache/kafka/clients/consumer/RangeAssignor.html).  See what happens when try using another provided assignor, such as the `StickyAssignor` (https://kafka.apache.org/23/javadoc/org/apache/kafka/clients/consumer/StickyAssignor.html).

**Comment by jsbrucker** [comment]
This seems to be the expected "normal behavior" for legacy compatibility reasons (if you have an always on system, there is a procedure to rollout the change in strategy).

I have found that you can use:
```
.withProperty(
   // Equivalent to "partition.assignment.strategy"
  org.apache.kafka.clients.consumer.ConsumerConfig.PARTITION_ASSIGNMENT_STRATEGY_CONFIG,
  // We want the name of the org.apache.kafka.clients.consumer.CooperativeStickyAssignor class
  // either using the the String directly or using getName on the type.
  "CooperativeStickyAssignor"
)
```
when configuring `akka.kafka.ConsumerSettings`. NOTE: it is probably possible to set this value in the typesafe Config.

After making the change above, when new consumers are added/removed, the rebalance only seems to impact partitions that need to be moved while the others continue processing.

**Comment by ennru** [comment]
Thank you, @jsbrucker for updating this issue with these details.
I guess it is time for Alpakka Kafka to default to the `CooperativeStickyAssignor` in the next release.

**Comment by patriknw** [comment]
@jsbrucker Do you have any insight to how such change would work during a rolling update when old nodes have the other (default) strategy? Any risk of wrong partition assignments (multiple consumers of same partition)?

Seems like compatibility has been the main reason for not changing the default in Kafka, see https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=177048248

If that is the case we should not change the default, but we can add a recommendation to the documentation with caveat about rolling updates.

**Comment by jsbrucker** [comment]
@patriknw

My recommendation above isn't compatible with a rolling upgrade, but there is documentation for it from Kafka (linked below). Unfortunately, rolling upgrades aren't an area where I have first hand experience (with Alpakka or otherwise).

* [Rolling Upgrade Procedure](https://cwiki.apache.org/confluence/display/KAFKA/KIP-429%3A+Kafka+Consumer+Incremental+Rebalance+Protocol#KIP429:KafkaConsumerIncrementalRebalanceProtocol-Consumer)
* [Dynamic Protocol Selection](https://issues.apache.org/jira/browse/KAFKA-12477)

**Comment by patriknw** [comment]
Thanks

**Comment by ennru** [comment]
## Since Kafka 2.4.0

To upgrade from the old (eager) protocol, which always revokes all partitions before rebalancing, to cooperative rebalancing, you must follow a specific upgrade path to get all clients on the same ConsumerPartitionAssignor that supports the cooperative protocol. This can be done with two rolling bounces, using the CooperativeStickyAssignor for the example: during the first one, add "cooperative-sticky" to the list of supported assignors for each member (without removing the previous assignor -- note that if previously using the default, you must include that explicitly as well). You then bounce and/or upgrade it. Once the entire group is on 2.4+ and all members have the "cooperative-sticky" among their supported assignors, remove the other assignor(s) and perform a second rolling bounce so that by the end all members support only the cooperative protocol. For further details on the cooperative rebalancing protocol and upgrade path, see [KIP-429](https://cwiki.apache.org/confluence/x/vAclBg).

From https://kafka.apache.org/documentation/#upgrade_240_notable

## Since Kafka 3.0.0

The default partition.assignment.strategy is changed to "[RangeAssignor, CooperativeStickyAssignor]", which will use the RangeAssignor by default, but allows upgrading to the CooperativeStickyAssignor with just a single rolling bounce that removes the RangeAssignor from the list. Please check the client upgrade path guide [here](https://cwiki.apache.org/confluence/display/KAFKA/KIP-429:+Kafka+Consumer+Incremental+Rebalance+Protocol#KIP429:KafkaConsumerIncrementalRebalanceProtocol-Consumer) for more detail.

From https://kafka.apache.org/33/documentation.html#upgrade_300_notable

**Comment by ennru** [comment]
Confluent blog 
https://www.confluent.io/blog/cooperative-rebalancing-in-kafka-streams-consumer-ksqldb/

conduktor article
https://www.conduktor.io/kafka/consumer-incremental-rebalance-and-static-group-membership

**Comment by ennru** [comment]
We've now added direct access to configure the assignment strategies with #1598 but will not change anything by default as upgrades need to be considered when changing the strategy.
